apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: fastapi
        image: ihorek/backend:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: models
          mountPath: /app/data
      volumes:
      - name: models
        hostPath:
          path: /app/data
          type: Directory